final

diff --git a/gitops/Jenkinsfile b/gitops/Jenkinsfile
--- a/gitops/Jenkinsfile
+++ b/gitops/Jenkinsfile
@@ -95,20 +95,22 @@ pipeline {
         stage('Terraform Plan') {
             steps {
                 dir('terraform') {
-                    script {
-                        def status = sh(
-                            script: 'terraform plan -detailed-exitcode -out=tfplan || true',
-                            returnStatus: true
-                        )
-                        echo "Terraform plan exit code: ${status}"
+                    withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds']]) {
+                        script {
+                            def planExit = sh(
+                                script: 'terraform plan -detailed-exitcode -out=tfplan || true',
+                                returnStatus: true
+                            )
+                            echo "Terraform plan exit code: ${planExit}"
 
-                        if (status == 2) {
-                            env.TF_CHANGES = "true"
-                            currentBuild.description = "Terraform: Changes Detected"
-                        } else if (status == 0) {
-                            echo "✅ No infrastructure changes."
-                        } else {
-                            error "❌ Terraform plan failed with exit code ${status}"
+                            if (planExit == 2) {
+                                sh 'touch .tf_changes'
+                                currentBuild.description = "Terraform: Changes Detected"
+                            } else if (planExit == 0) {
+                                echo "✅ No changes detected"
+                            } else {
+                                error "❌ Terraform plan failed with exit code ${planExit}"
+                            }
                         }
                     }
                 }
@@ -117,7 +119,9 @@ pipeline {
 
         stage('Terraform Apply') {
             when {
-                expression { env.TF_CHANGES == 'true' }
+                expression {
+                    return fileExists('terraform/.tf_changes')
+                }
             }
             steps {
                 dir('terraform') {
@@ -128,7 +132,7 @@ pipeline {
                 }
             }
         }
-        
+
         // stage('Post Apply Audit') {
         //     when {
         //         expression { env.TF_CHANGES == "true" }
@@ -188,6 +192,13 @@ pipeline {
                     docker rmi $DOCKER_USER/mern-app-frontend:v${params.PARENT_BUILD_NUMBER}
                     docker rmi $DOCKER_USER/mern-app-backend:v${params.PARENT_BUILD_NUMBER}
                 """
+            }
+        }
+    }
+    post {
+        always {
+            dir('terraform') {
+                sh 'rm -f .tf_changes tfplan || true'
             }
         }
     }
